config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :addresses

end

app/models/address.rb
class Address < ActiveRecord::Base
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def index
    @addresses = Address.all
  end
  def new
    @address = Address.new
  end
  def create
    @address = Address.new(address_params)
    if @address.save
      redirect_to addresses_path
    else

      render :new
    end
  end
  def edit
    @address = Address.find(params[:id])

  end

  def show
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.new(address_params)
    if @address.update(address_params)
      redirect_to addresses_path
    else
      render :edit
    end
  end

  def destroy
    address = Address.find(params[:id])
    address.destroy
    redirect_to addresses_path

  end




  private

  def address_params
    params.require(:address).permit(:name, :address_line_one, :address_line_two, :city, :state, :zipcode, :phone_number)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/edit.html.erb
<%=form_for @address do |f| %>

<div>
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div>
  <%= f.label :address_line_one %>
  <%= f.text_field :address_line_one %>
</div>

<div>
  <%= f.label :address_line_two %>
  <%= f.text_field :address_line_two %>
</div>

<div>
  <%= f.label :city %>
  <%= f.text_field :city %>
</div>

<div>
  <%= f.label :state %>
  <%= f.text_field :state %>
</div>

<div>
 <%= f.label :zipcode %>
 <%= f.number_field :zipcode %>
</div>
<div>
  <%= f.label :phone_number %>
  <%= f.number_field :phone_number %>
</div>

  <%= f.submit "Update Address" %>
<% end %>

app/views/addresses/index.html.erb
<% @addresses.each do |address| %>
<%= link_to 'View Address', address_path(address) %>
<br>
<%= address.name %>
<br>
<%= address.address_line_one %>
<br>
<%= address.address_line_two %>
<br>
<%= address.city %>
<br>
<%= address.state %>
<br>
<%= address.zipcode %>
<br>
<%= address.phone_number %>
<hr>
<%end%>

<%= link_to 'Add a new address',new_address_path %>

app/views/addresses/new.html.erb
<%=form_for @address do |f| %>

<div>
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div>
  <%= f.label :address_line_one %>
  <%= f.text_field :address_line_one %>
</div>

<div>
  <%= f.label :address_line_two %>
  <%= f.text_field :address_line_two %>
</div>

<div>
  <%= f.label :city %>
  <%= f.text_field :city %>
</div>

<div>
  <%= f.label :state %>
  <%= f.text_field :state %>
</div>

<div>
 <%= f.label :zipcode %>
 <%= f.number_field :zipcode %>
</div>
<div>
  <%= f.label :phone_number %>
  <%= f.number_field :phone_number %>
</div>

  <%= f.submit "Add Address" %>
<% end %>

app/views/addresses/show.html.erb
<%= @address.name %>
<br>
<%= @address.address_line_one %>
<br>
<%= @address.address_line_two %>
<br>
<%= @address.city %>
<br>
<%= @address.state %>
<br>
<%= @address.zipcode %>
<br>
<%= @address.phone_number %>
<hr>
<%= link_to 'Edit', edit_address_path(@address) %>
<%= link_to "Delete this post", address_path(@address), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FormPractice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
HELLO!

<%= link_to 'LOOK at these ADDRESSES',addresses_path %>